import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { convertToBase64 } from "@/utils/convertToBase64";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleSubmit = async (e: any) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const data = Object.fromEntries(formData);
    console.log(data);

    // convert data to formdata

    // append file;

    fetch("/api/submit", {
      method: "POST",
      body: JSON.stringify({
        ...data,
        myfile: await convertToBase64(data.myfile as any),
      }),
      headers: {
        "Content-Type": "application/json",
      },
    })
      .then((res) => {
        console.log("res", res);
      })
      .catch((err) => {
        console.log("err", err);
      });
  };

  const getFileType = (file: any) => {
    const type = file.type;
    const typeArray = type.split("/");
    return typeArray[1];
  };
  return (
    <>
      <Head>
        <title>JECRC</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="style.css"></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <h1>AIAMMS Manuscript Submission -2023</h1>

          <form onSubmit={handleSubmit}>
            <div className="row">
              <div className="column">
                <label htmlFor="email">Email</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  placeholder="Your email here"
                  required
                />
              </div>
              <div className="column">
                <label htmlFor="subject">Title of Paper</label>
                <input
                  type="text"
                  id="subject"
                  name="subject"
                  placeholder="Your Answer"
                  required
                />
              </div>
              <div className="column">
                <label htmlFor="name">Name</label>
                <input
                  type="name"
                  id="name"
                  name="name"
                  placeholder="Your Name here"
                  required
                />
              </div>
            </div>
            <div className="row">
              <div className="column">
                <label htmlFor="abstract">Abstract of Paper</label>
                <input
                  type="text"
                  id="subject"
                  name="abstract"
                  placeholder="Your Answer"
                  required
                />
              </div>
              <div className="column">
                <label htmlFor="keywords">Keywords of Paper</label> <br />
                <input
                  type="text"
                  id="keywords"
                  name="keywords"
                  placeholder="Your Answer"
                  required
                />
              </div>
              <div className="column">
                <label htmlFor="affiliation">
                  Full Affiliation with pin code
                </label>
                <input
                  type="text"
                  id="affiliation"
                  name="affiliation"
                  placeholder="Your Answer"
                  required
                />
              </div>
            </div>
            <div className="row">
              <div className="column">
                <label htmlFor="designation">Designation</label> <br />
                <input
                  type="text"
                  id="designation"
                  name="designation"
                  placeholder="Your Answer"
                  required
                />
              </div>
              <div className="column">
                <label htmlFor="mobile">Mobile Number with Country Code</label>
                <input
                  type="text"
                  id="mobile"
                  name="mobile"
                  placeholder="Your Answer"
                  required
                />
              </div>
              <div className="column">
                <label htmlFor="countrycode">
                  Whats app Number with Country Code
                </label>
                <input
                  type="text"
                  id="countrycode"
                  name="countrycode"
                  placeholder="Your Answer"
                  required
                />
              </div>
            </div>
            <div className="row">
              <div className="column">
                <label>
                  Track of AIAMMS 2023, in which you feel that your article is
                  suitable:
                </label>
                <br />
                <input
                  type="radio"
                  id="Artificial Intelligence"
                  name="drone"
                  value="Artificial Intelligence (AI)"
                  checked
                />
                <label htmlFor="huey"> Artificial Intelligence (AI)</label>
                <br />
                <input
                  type="radio"
                  id="Advanced Manufacturing & Industrial Engineering"
                  name="drone"
                  value="Advanced Manufacturing & Industrial Engineering"
                  checked
                />
                <label htmlFor="Advanced Manufacturing & Industrial Engineering">
                  {" "}
                  Advanced Manufacturing & Industrial Engineering
                </label>
                <br />
                <input
                  type="radio"
                  id="Advanced Materials"
                  name="drone"
                  value="Advanced Materials"
                  checked
                />
                <label htmlFor="Advanced Materials"> Advanced Materials</label>
                <br />
                <input
                  type="radio"
                  id="Mechatronics System"
                  name="drone"
                  value="Mechatronics System"
                  checked
                />
                <label htmlFor="Mechatronics System">
                  {" "}
                  Mechatronics System
                </label>
                <br />
                <input
                  type="radio"
                  id="Smart and Electrical Vehicles"
                  name="drone"
                  value="Smart and Electrical Vehicles"
                  checked
                />
                <label htmlFor="Smart and Electrical Vehicles">
                  {" "}
                  Smart and Electrical Vehicles
                </label>
                <br />
              </div>
            </div>
            <div className="row">
              <div className="column">
                <label htmlFor="radio">
                  Publication Category (where you want to get registered- please
                  see Publication and Registration Tab htmlFor this)
                </label>
                <br />
                <input
                  type="radio"
                  id="Category A"
                  name="drone2"
                  value="Category A"
                  checked
                />
                <label htmlFor="Category A"> Category A</label>
                <br />
                <input
                  type="radio"
                  id="Category B & C"
                  name="drone2"
                  value="Category B & C"
                  checked
                />
                <label htmlFor="Category B & C"> Category B & C</label>
                <br />
              </div>
            </div>

            <div className="row">
              <div className="column">
                <label htmlFor="radio">
                  Upload full length manuscript here in word htmlFormat (Max 10
                  MB)
                </label>
                <br />
                <input
                  type="file"
                  id="myfile"
                  name="myfile"
                  required
                  accept=".doc, .docx, .pdf"
                />
              </div>
            </div>
            <div className="row">
              <div className="column">
                <label htmlFor="specialRequirements">
                  Do you have any special requirements / requests? Please write
                  here
                </label>
                <br />
                <textarea
                  id="specialRequirements"
                  name="specialRequirements"
                  rows={4}
                  cols={50}
                ></textarea>
              </div>
            </div>
            <div className="row">
              <div className="column">
                <input
                  type="checkbox"
                  id="terms"
                  name="terms"
                  value="terms"
                  required
                />
                <label htmlFor="terms">
                  {" "}
                  I accept that this research work is original and has not been
                  published anywhere and nor it is under communication or
                  consideration anywhere else. I will not submit this work
                  anywhere else until this is under consideration in AIAMMS
                  2023.
                </label>
                <br />
              </div>
            </div>

            <button>Submit</button>
          </form>
        </div>
      </main>
    </>
  );
}
